name: "ZallDataSDK CI"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
jobs:
  Build:
    name: carthage build
    runs-on: macos-11
    if: startsWith(github.ref, 'refs/tags/')
    env:
      SCHEME_NAME: ZallDataSDK
      DEVELOPER_DIR: /Applications/Xcode_13.0.app
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build as static Library # carthage build --archive
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          carthage build --archive

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.SCHEME_NAME }}.framework.zip

      - name: Deploy to Cocoapods
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
